name: Deploy to Snowflake

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install SnowCLI
        run: |
          pip install --user snowflake-cli
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure SnowCLI
        run: |
          mkdir -p ~/.snowflake
          cat << EOF > ~/.snowflake/config.toml
          [connections.default]
          account = "iiljdbv-rv91789"
          user = "SAGARK"
          password = "Infyme@25011998"
          role = "ACCOUNTADMIN"
          database = "DEVOPS"
          warehouse = "COMPUTE_WH"
          EOF
          chmod 600 ~/.snowflake/config.toml

      - name: Test Snowflake Connection
        run: snow connection test --connection default

      - name: Deploy schema creation script
        run: |
          if [ -f scripts/create_schemas.sql ]; then
            echo "Creating schemas..."
            snow sql -f scripts/create_schemas.sql --connection default
          else
            echo "No schema creation script found."
          fi

      - name: Deploy SQL files under schemas/
        run: |
          echo "Deploying all SQL files under schemas/..."
          find schemas -type f -name "*.sql" | while read file; do
            echo "Deploying $file"
            snow sql -f "$file" --connection default
          done
