name: Deploy to Snowflake on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed for full diff

      - name: Set environment variables
        run: |
          echo "BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
          echo "HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Get changed SQL files
        id: detect_changes
        run: |
          CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep '\.sql$' || true)
          echo "Changed SQL files:"
          echo "$CHANGED_FILES"

          if [[ -z "$CHANGED_FILES" ]]; then
            echo "DEPLOY_ALL=true" >> $GITHUB_ENV
          else
            echo "$CHANGED_FILES" > changed_files.txt
            echo "DEPLOY_ALL=false" >> $GITHUB_ENV
          fi

      - name: Set up Python and SnowCLI
        run: |
          pip install --user snowflake-cli
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure SnowCLI
        run: |
          mkdir -p ~/.snowflake
          cat <<EOF > ~/.snowflake/config.toml
          [connections.default]
          account = "your_account"
          user = "your_user"
          password = "your_password"
          role = "your_role"
          warehouse = "your_warehouse"
          database = "your_db"
          EOF

      - name: Deploy SQL files
        run: |
          echo "Deploying tables..."
          if [[ "$DEPLOY_ALL" == "true" ]]; then
            find schemas -type f -path "*/tables/*.sql" | sort | while read file; do
              echo "Deploying $file"
              snow sql -f "$file" --connection default
            done
          else
            grep 'tables/' changed_files.txt | while read file; do
              echo "Deploying changed table: $file"
              snow sql -f "$file" --connection default
            done
          fi

      # Repeat similar blocks for views and other objects...
